# Generated by Django 5.0 on 2024-10-16 05:05

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortgroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='program',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='program',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='program',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='Default Program', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.CharField(default='Default Cohort', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
       migrations.AddField(
    model_name='student',
    name='program',
    field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.program'),  # Change `2` to the actual id
    preserve_default=False,
),
 

        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cohortgroup',
            name='date_join',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cohortgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='date_join',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
