# Generated by Django 5.0 on 2024-10-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.URLField(default='default', verbose_name='Profile Image URL'),
            preserve_default=False,
        ),
    ]
